/*
  Catalogue de consommation moyenne par modèle, dérivé du jeu de données officiel ADEME Car
  Labelling (data.gouv.fr, licence ouverte), agrégé aux 178 couples marque/modèle du
  trimestre en cours. Ne couvre que les modèles commercialisés neufs aujourd'hui — ni les
  générations précédentes (Golf 7, Clio 4…) ni les modèles retirés du catalogue ce
  trimestre (Golf, Polo actuelles). lookupCarConsumption sert de suggestion, jamais de
  vérité : le champ Consommation reste éditable, rien n'est réécrit si une valeur y est déjà.
*/
const CAR_CONSUMPTION_DB = [
  { brand: 'Alfa Romeo', model: 'Giulia', fuel: 'petrol', gearbox: 'automatic', consumption: '6,5' },
  { brand: 'Alfa Romeo', model: 'Stelvio', fuel: 'diesel', gearbox: 'automatic', consumption: '6,7' },
  { brand: 'Alpine', model: 'A110', fuel: 'petrol', gearbox: 'automatic', consumption: '6,9' },
  { brand: 'Audi', model: 'A3', fuel: 'hybrid', gearbox: 'automatic', consumption: '4,9' },
  { brand: 'Audi', model: 'E-Tron Gt', fuel: 'electric', gearbox: 'automatic', consumption: '' },
  { brand: 'Audi', model: 'Q3', fuel: 'petrol', gearbox: 'manual', consumption: '6,4' },
  { brand: 'BMW', model: '116', fuel: 'petrol', gearbox: 'automatic', consumption: '6,2' },
  { brand: 'BMW', model: '118', fuel: 'petrol', gearbox: 'automatic', consumption: '6,2' },
  { brand: 'BMW', model: '120', fuel: 'petrol', gearbox: 'automatic', consumption: '6,4' },
  { brand: 'BMW', model: '128', fuel: 'petrol', gearbox: 'automatic', consumption: '7,2' },
  { brand: 'BMW', model: '135', fuel: 'petrol', gearbox: 'automatic', consumption: '7,7' },
  { brand: 'BMW', model: '218', fuel: 'petrol', gearbox: 'automatic', consumption: '6,0' },
  { brand: 'BMW', model: '220', fuel: 'petrol', gearbox: 'automatic', consumption: '6,3' },
  { brand: 'BMW', model: '225', fuel: 'hybrid', gearbox: 'automatic', consumption: '0,7' },
  { brand: 'BMW', model: '235', fuel: 'petrol', gearbox: 'automatic', consumption: '7,5' },
  { brand: 'BMW', model: '240', fuel: 'petrol', gearbox: 'automatic', consumption: '8,5' },
  { brand: 'BMW', model: '316', fuel: 'hybrid', gearbox: 'automatic', consumption: '5,4' },
  { brand: 'BMW', model: '318', fuel: 'hybrid', gearbox: 'automatic', consumption: '5,9' },
  { brand: 'BMW', model: '320', fuel: 'hybrid', gearbox: 'automatic', consumption: '4,5' },
  { brand: 'BMW', model: '330', fuel: 'hybrid', gearbox: 'automatic', consumption: '3,8' },
  { brand: 'BMW', model: '340', fuel: 'hybrid', gearbox: 'automatic', consumption: '6,9' },
  { brand: 'BMW', model: '420', fuel: 'hybrid', gearbox: 'automatic', consumption: '5,9' },
  { brand: 'BMW', model: '430', fuel: 'hybrid', gearbox: 'automatic', consumption: '5,7' },
  { brand: 'BMW', model: '440', fuel: 'hybrid', gearbox: 'automatic', consumption: '7,6' },
  { brand: 'BMW', model: '518', fuel: 'hybrid', gearbox: 'automatic', consumption: '5,4' },
  { brand: 'BMW', model: '520', fuel: 'hybrid', gearbox: 'automatic', consumption: '5,9' },
  { brand: 'BMW', model: '530', fuel: 'hybrid', gearbox: 'automatic', consumption: '3,4' },
  { brand: 'BMW', model: '540', fuel: 'hybrid', gearbox: 'automatic', consumption: '6,2' },
  { brand: 'BMW', model: '840', fuel: 'hybrid', gearbox: 'automatic', consumption: '7,3' },
  { brand: 'BMW', model: '850', fuel: 'petrol', gearbox: 'automatic', consumption: '10,7' },
  { brand: 'BMW', model: 'IX3', fuel: 'electric', gearbox: 'automatic', consumption: '' },
  { brand: 'BMW', model: 'Ix', fuel: 'electric', gearbox: 'automatic', consumption: '' },
  { brand: 'BMW', model: 'M3', fuel: 'petrol', gearbox: 'automatic', consumption: '10,0' },
  { brand: 'BMW', model: 'M4', fuel: 'petrol', gearbox: 'automatic', consumption: '10,0' },
  { brand: 'BMW', model: 'M8', fuel: 'petrol', gearbox: 'automatic', consumption: '11,3' },
  { brand: 'BMW', model: 'X1', fuel: 'petrol', gearbox: 'automatic', consumption: '6,1' },
  { brand: 'BMW', model: 'X2', fuel: 'petrol', gearbox: 'automatic', consumption: '6,2' },
  { brand: 'BMW', model: 'X3', fuel: 'hybrid', gearbox: 'automatic', consumption: '6,8' },
  { brand: 'BMW', model: 'X4', fuel: 'hybrid', gearbox: 'automatic', consumption: '7,2' },
  { brand: 'BMW', model: 'Z4', fuel: 'petrol', gearbox: 'automatic', consumption: '7,1' },
  { brand: 'Citroen', model: 'Berlingo', fuel: 'diesel', gearbox: 'manual', consumption: '5,4' },
  { brand: 'Citroen', model: 'C3', fuel: 'petrol', gearbox: 'manual', consumption: '5,5' },
  { brand: 'Citroen', model: 'C3 Aircross', fuel: 'diesel', gearbox: 'automatic', consumption: '5,1' },
  { brand: 'Citroen', model: 'C4', fuel: 'diesel', gearbox: 'manual', consumption: '4,4' },
  { brand: 'Citroen', model: 'C4 X', fuel: 'diesel', gearbox: 'automatic', consumption: '5,0' },
  { brand: 'Citroen', model: 'C5 Aircross', fuel: 'hybrid', gearbox: 'automatic', consumption: '1,5' },
  { brand: 'Citroen', model: 'C5 X', fuel: 'petrol', gearbox: 'automatic', consumption: '6,9' },
  { brand: 'Citroen', model: 'Space Tourer', fuel: 'electric', gearbox: 'automatic', consumption: '' },
  { brand: 'Cupra', model: 'Formentor', fuel: 'petrol', gearbox: 'automatic', consumption: '7,7' },
  { brand: 'DS', model: '3 Crossback', fuel: 'diesel', gearbox: 'automatic', consumption: '5,1' },
  { brand: 'DS', model: '4', fuel: 'petrol', gearbox: 'automatic', consumption: '6,9' },
  { brand: 'DS', model: '7 Crossback', fuel: 'hybrid', gearbox: 'automatic', consumption: '1,5' },
  { brand: 'DS', model: '9', fuel: 'petrol', gearbox: 'automatic', consumption: '4,7' },
  { brand: 'Dacia', model: 'Jogger', fuel: 'petrol', gearbox: 'manual', consumption: '6,6' },
  { brand: 'Dacia', model: 'Lodgy', fuel: 'diesel', gearbox: 'manual', consumption: '4,9' },
  { brand: 'Dacia', model: 'Sandero', fuel: 'petrol', gearbox: 'manual', consumption: '6,0' },
  { brand: 'Dacia', model: 'Spring', fuel: 'electric', gearbox: 'automatic', consumption: '' },
  { brand: 'Ferrari', model: '812', fuel: 'petrol', gearbox: 'manual', consumption: '16,6' },
  { brand: 'Ferrari', model: 'F8', fuel: 'petrol', gearbox: 'manual', consumption: '12,9' },
  { brand: 'Ferrari', model: 'Monza', fuel: 'petrol', gearbox: 'manual', consumption: '16,1' },
  { brand: 'Fiat', model: '500', fuel: 'hybrid', gearbox: 'manual', consumption: '5,1' },
  { brand: 'Fiat', model: 'Panda', fuel: 'hybrid', gearbox: 'manual', consumption: '5,1' },
  { brand: 'Ford', model: 'Ecosport', fuel: 'petrol', gearbox: 'manual', consumption: '6,3' },
  { brand: 'Ford', model: 'Explorer', fuel: 'hybrid', gearbox: 'automatic', consumption: '3,1' },
  { brand: 'Ford', model: 'Fiesta', fuel: 'petrol', gearbox: 'manual', consumption: '7,0' },
  { brand: 'Ford', model: 'Focus', fuel: 'hybrid', gearbox: 'manual', consumption: '5,5' },
  { brand: 'Ford', model: 'Galaxy', fuel: 'hybrid', gearbox: 'automatic', consumption: '6,5' },
  { brand: 'Ford', model: 'Gt', fuel: 'petrol', gearbox: 'automatic', consumption: '13,7' },
  { brand: 'Ford', model: 'Kuga', fuel: 'hybrid', gearbox: 'automatic', consumption: '4,9' },
  { brand: 'Ford', model: 'Mustang', fuel: 'petrol', gearbox: 'automatic', consumption: '11,4' },
  { brand: 'Ford', model: 'S-Max', fuel: 'hybrid', gearbox: 'automatic', consumption: '6,5' },
  { brand: 'Ford', model: 'Tourneo Connect', fuel: 'diesel', gearbox: 'manual', consumption: '5,5' },
  { brand: 'Ford', model: 'Transit Custom', fuel: 'diesel', gearbox: 'manual', consumption: '8,2' },
  { brand: 'Honda', model: 'Civic', fuel: 'hybrid', gearbox: 'automatic', consumption: '5,0' },
  { brand: 'Honda', model: 'Cr-V', fuel: 'hybrid', gearbox: 'automatic', consumption: '6,8' },
  { brand: 'Honda', model: 'E', fuel: 'electric', gearbox: 'automatic', consumption: '' },
  { brand: 'Honda', model: 'Hr-V', fuel: 'hybrid', gearbox: 'automatic', consumption: '5,4' },
  { brand: 'Honda', model: 'Jazz', fuel: 'hybrid', gearbox: 'automatic', consumption: '4,7' },
  { brand: 'Hyundai', model: 'I 10', fuel: 'petrol', gearbox: 'manual', consumption: '5,3' },
  { brand: 'Hyundai', model: 'I 30', fuel: 'hybrid', gearbox: 'manual', consumption: '5,8' },
  { brand: 'Hyundai', model: 'Santa Fe', fuel: 'hybrid', gearbox: 'automatic', consumption: '6,2' },
  { brand: 'Hyundai', model: 'Tucson', fuel: 'hybrid', gearbox: 'automatic', consumption: '5,5' },
  { brand: 'Jeep', model: 'Compass', fuel: 'hybrid', gearbox: 'automatic', consumption: '3,1' },
  { brand: 'Jeep', model: 'Renegade', fuel: 'hybrid', gearbox: 'manual', consumption: '4,5' },
  { brand: 'Kia', model: 'Ceed', fuel: 'hybrid', gearbox: 'automatic', consumption: '5,0' },
  { brand: 'Kia', model: 'EV6', fuel: 'electric', gearbox: 'automatic', consumption: '' },
  { brand: 'Kia', model: 'Niro', fuel: 'hybrid', gearbox: 'automatic', consumption: '3,3' },
  { brand: 'Kia', model: 'Picanto', fuel: 'petrol', gearbox: 'manual', consumption: '5,3' },
  { brand: 'Kia', model: 'Proceed', fuel: 'petrol', gearbox: 'manual', consumption: '6,1' },
  { brand: 'Kia', model: 'Rio', fuel: 'petrol', gearbox: 'manual', consumption: '5,5' },
  { brand: 'Kia', model: 'Sorento', fuel: 'hybrid', gearbox: 'automatic', consumption: '5,5' },
  { brand: 'Kia', model: 'Soul', fuel: 'electric', gearbox: 'automatic', consumption: '' },
  { brand: 'Kia', model: 'Sportage', fuel: 'hybrid', gearbox: 'automatic', consumption: '5,6' },
  { brand: 'Kia', model: 'Stonic', fuel: 'hybrid', gearbox: 'manual', consumption: '5,5' },
  { brand: 'Kia', model: 'Xceed', fuel: 'hybrid', gearbox: 'automatic', consumption: '4,6' },
  { brand: 'Lamborghini', model: 'Aventador', fuel: 'petrol', gearbox: 'automatic', consumption: '18,4' },
  { brand: 'Lamborghini', model: 'Urus', fuel: 'petrol', gearbox: 'automatic', consumption: '12,7' },
  { brand: 'Land Rover', model: 'Defender', fuel: 'hybrid', gearbox: 'automatic', consumption: '2,8' },
  { brand: 'Lexus', model: 'Nx', fuel: 'hybrid', gearbox: 'automatic', consumption: '7,3' },
  { brand: 'Lexus', model: 'Rx', fuel: 'hybrid', gearbox: 'automatic', consumption: '7,9' },
  { brand: 'MG', model: 'Marvel', fuel: 'electric', gearbox: 'automatic', consumption: '' },
  { brand: 'MG', model: 'Zs', fuel: 'petrol', gearbox: 'manual', consumption: '6,6' },
  { brand: 'Maserati', model: 'Ghibli', fuel: 'hybrid', gearbox: 'automatic', consumption: '9,0' },
  { brand: 'Maserati', model: 'Grecale', fuel: 'hybrid', gearbox: 'automatic', consumption: '9,4' },
  { brand: 'Mazda', model: 'CX-5', fuel: 'diesel', gearbox: 'automatic', consumption: '6,3' },
  { brand: 'Mazda', model: 'CX-60', fuel: 'hybrid', gearbox: 'automatic', consumption: '1,6' },
  { brand: 'Mazda', model: 'MX-30', fuel: 'electric', gearbox: 'automatic', consumption: '' },
  { brand: 'Mercedes', model: 'E 200', fuel: 'hybrid', gearbox: 'automatic', consumption: '5,5' },
  { brand: 'Mercedes', model: 'E 300', fuel: 'hybrid', gearbox: 'automatic', consumption: '1,4' },
  { brand: 'Mercedes', model: 'E 400', fuel: 'diesel', gearbox: 'automatic', consumption: '6,8' },
  { brand: 'Mercedes', model: 'E 53 Amg', fuel: 'hybrid', gearbox: 'automatic', consumption: '9,4' },
  { brand: 'Mercedes', model: 'Eqa 250', fuel: 'electric', gearbox: 'automatic', consumption: '' },
  { brand: 'Mercedes', model: 'Eqa 350', fuel: 'electric', gearbox: 'automatic', consumption: '' },
  { brand: 'Mercedes', model: 'Eqb 350', fuel: 'electric', gearbox: 'automatic', consumption: '' },
  { brand: 'Mini', model: 'Cabrio', fuel: 'petrol', gearbox: 'automatic', consumption: '6,3' },
  { brand: 'Mini', model: 'Clubman', fuel: 'petrol', gearbox: 'automatic', consumption: '6,4' },
  { brand: 'Mini', model: 'Countryman', fuel: 'petrol', gearbox: 'automatic', consumption: '6,3' },
  { brand: 'Mini', model: 'Mini', fuel: 'petrol', gearbox: 'automatic', consumption: '6,1' },
  { brand: 'Mitsubishi', model: 'Space Star', fuel: 'petrol', gearbox: 'manual', consumption: '5,2' },
  { brand: 'Nissan', model: 'Ariya', fuel: 'electric', gearbox: 'automatic', consumption: '' },
  { brand: 'Nissan', model: 'Juke', fuel: 'petrol', gearbox: 'automatic', consumption: '6,0' },
  { brand: 'Nissan', model: 'Leaf', fuel: 'electric', gearbox: 'automatic', consumption: '' },
  { brand: 'Nissan', model: 'Micra', fuel: 'petrol', gearbox: 'manual', consumption: '5,8' },
  { brand: 'Nissan', model: 'Primastar', fuel: 'diesel', gearbox: 'manual', consumption: '7,3' },
  { brand: 'Nissan', model: 'Qashqai', fuel: 'hybrid', gearbox: 'manual', consumption: '6,5' },
  { brand: 'Nissan', model: 'Townstar', fuel: 'petrol', gearbox: 'manual', consumption: '7,2' },
  { brand: 'Opel', model: 'Corsa', fuel: 'petrol', gearbox: 'manual', consumption: '5,3' },
  { brand: 'Opel', model: 'Crossland X', fuel: 'petrol', gearbox: 'manual', consumption: '5,3' },
  { brand: 'Opel', model: 'Grandland', fuel: 'diesel', gearbox: 'automatic', consumption: '5,4' },
  { brand: 'Opel', model: 'Mokka', fuel: 'petrol', gearbox: 'manual', consumption: '5,7' },
  { brand: 'Peugeot', model: '2008', fuel: 'diesel', gearbox: 'automatic', consumption: '4,9' },
  { brand: 'Peugeot', model: '208', fuel: 'petrol', gearbox: 'manual', consumption: '5,0' },
  { brand: 'Peugeot', model: '3008', fuel: 'hybrid', gearbox: 'automatic', consumption: '1,5' },
  { brand: 'Peugeot', model: '308', fuel: 'diesel', gearbox: 'manual', consumption: '5,1' },
  { brand: 'Peugeot', model: '508', fuel: 'hybrid', gearbox: 'automatic', consumption: '3,1' },
  { brand: 'Peugeot', model: 'Rifter', fuel: 'diesel', gearbox: 'manual', consumption: '5,6' },
  { brand: 'Peugeot', model: 'Traveller', fuel: 'electric', gearbox: 'automatic', consumption: '' },
  { brand: 'Porsche', model: '911', fuel: 'petrol', gearbox: 'automatic', consumption: '11,2' },
  { brand: 'Porsche', model: 'Macan', fuel: 'petrol', gearbox: 'automatic', consumption: '11,0' },
  { brand: 'Porsche', model: 'Panamera', fuel: 'hybrid', gearbox: 'automatic', consumption: '2,3' },
  { brand: 'Porsche', model: 'Taycan', fuel: 'electric', gearbox: 'automatic', consumption: '' },
  { brand: 'Renault', model: 'Arkana', fuel: 'hybrid', gearbox: 'automatic', consumption: '5,4' },
  { brand: 'Renault', model: 'Austral', fuel: 'hybrid', gearbox: 'automatic', consumption: '6,4' },
  { brand: 'Renault', model: 'Captur', fuel: 'hybrid', gearbox: 'automatic', consumption: '5,6' },
  { brand: 'Renault', model: 'Clio', fuel: 'petrol', gearbox: 'manual', consumption: '5,2' },
  { brand: 'Renault', model: 'Espace', fuel: 'diesel', gearbox: 'automatic', consumption: '6,3' },
  { brand: 'Renault', model: 'Kangoo', fuel: 'petrol', gearbox: 'manual', consumption: '6,6' },
  { brand: 'Renault', model: 'Koleos', fuel: 'petrol', gearbox: 'automatic', consumption: '6,8' },
  { brand: 'Renault', model: 'Megane', fuel: 'diesel', gearbox: 'automatic', consumption: '4,8' },
  { brand: 'Renault', model: 'Scenic', fuel: 'petrol', gearbox: 'manual', consumption: '6,6' },
  { brand: 'Renault', model: 'Talisman', fuel: 'diesel', gearbox: 'automatic', consumption: '6,0' },
  { brand: 'Renault', model: 'Trafic', fuel: 'diesel', gearbox: 'manual', consumption: '7,3' },
  { brand: 'Renault', model: 'Twingo', fuel: 'petrol', gearbox: 'manual', consumption: '5,2' },
  { brand: 'Renault', model: 'Zoe', fuel: 'electric', gearbox: 'automatic', consumption: '' },
  { brand: 'Rolls-Royce', model: 'Cullinan', fuel: 'petrol', gearbox: 'automatic', consumption: '16,5' },
  { brand: 'Rolls-Royce', model: 'Dawn', fuel: 'petrol', gearbox: 'automatic', consumption: '16,0' },
  { brand: 'Skoda', model: 'Kamiq', fuel: 'petrol', gearbox: 'automatic', consumption: '6,1' },
  { brand: 'Skoda', model: 'Karoq', fuel: 'petrol', gearbox: 'automatic', consumption: '6,0' },
  { brand: 'Skoda', model: 'Kodiaq', fuel: 'diesel', gearbox: 'automatic', consumption: '6,6' },
  { brand: 'Skoda', model: 'Octavia', fuel: 'hybrid', gearbox: 'automatic', consumption: '5,3' },
  { brand: 'Skoda', model: 'Scala', fuel: 'petrol', gearbox: 'automatic', consumption: '5,9' },
  { brand: 'Subaru', model: 'Forester', fuel: 'hybrid', gearbox: 'automatic', consumption: '8,1' },
  { brand: 'Subaru', model: 'Solterra', fuel: 'electric', gearbox: 'automatic', consumption: '' },
  { brand: 'Suzuki', model: 'Ignis', fuel: 'hybrid', gearbox: 'manual', consumption: '5,2' },
  { brand: 'Suzuki', model: 'SX4', fuel: 'hybrid', gearbox: 'manual', consumption: '5,8' },
  { brand: 'Suzuki', model: 'Swace', fuel: 'hybrid', gearbox: 'automatic', consumption: '4,7' },
  { brand: 'Suzuki', model: 'Swift', fuel: 'hybrid', gearbox: 'manual', consumption: '5,2' },
  { brand: 'Suzuki', model: 'Vitara', fuel: 'hybrid', gearbox: 'automatic', consumption: '6,2' },
  { brand: 'Tesla', model: 'Model 3', fuel: 'electric', gearbox: 'automatic', consumption: '' },
  { brand: 'Toyota', model: 'C-Hr', fuel: 'hybrid', gearbox: 'automatic', consumption: '5,2' },
  { brand: 'Toyota', model: 'Camry', fuel: 'hybrid', gearbox: 'automatic', consumption: '5,4' },
  { brand: 'Toyota', model: 'Yaris', fuel: 'hybrid', gearbox: 'automatic', consumption: '4,9' },
  { brand: 'Toyota', model: 'Yaris Cross', fuel: 'hybrid', gearbox: 'automatic', consumption: '4,8' },
  { brand: 'Volkswagen', model: 'Caddy', fuel: 'diesel', gearbox: 'automatic', consumption: '5,9' },
  { brand: 'Volkswagen', model: 'T-Roc', fuel: 'petrol', gearbox: 'automatic', consumption: '6,0' },
  { brand: 'Volkswagen', model: 'Touran', fuel: 'diesel', gearbox: 'automatic', consumption: '5,9' },
  { brand: 'Volvo', model: 'XC60', fuel: 'hybrid', gearbox: 'automatic', consumption: '6,3' },
  { brand: 'Volvo', model: 'XC90', fuel: 'hybrid', gearbox: 'automatic', consumption: '7,1' },
];

function normalizeCarText(text) {
  return ` ${(text || '')
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, '')
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, ' ')
    .trim()} `;
}

// Le modèle dont le nom normalisé le plus long apparaît dans le texte tapé l'emporte :
// "Yaris Cross" doit matcher Yaris Cross, pas juste Yaris.
function lookupCarConsumption(name) {
  const haystack = normalizeCarText(name);
  if (!haystack.trim()) return null;
  let best = null;
  let bestLength = 0;
  CAR_CONSUMPTION_DB.forEach((entry) => {
    const needle = normalizeCarText(entry.model);
    if (!needle.trim() || !haystack.includes(needle)) return;
    if (needle.length > bestLength) {
      best = entry;
      bestLength = needle.length;
    }
  });
  return best;
}
