// The emoji vocabulary of the board, searched by French keywords. A frozen list like
// PLAN_STATUSES: adding one happens here, never by hand in PLAN.md.
const EMOJIS = [
  { char: '🗺️', words: 'carte plan voyage itinéraire monde' },
  { char: '🧭', words: 'boussole direction nord orientation' },
  { char: '🧳', words: 'valise bagage départ voyage' },
  { char: '🎒', words: 'sac à dos randonnée école' },
  { char: '🛂', words: 'passeport contrôle frontière douane' },
  { char: '🛃', words: 'douane bagage contrôle' },
  { char: '🎫', words: 'billet ticket entrée place' },
  { char: '🎟️', words: 'billet entrée place spectacle' },
  { char: '📅', words: 'calendrier date jour planning' },
  { char: '🗓️', words: 'calendrier planning dates agenda' },
  { char: '⏰', words: 'réveil heure alarme horaire' },
  { char: '⏳', words: 'sablier attente à faire temps' },
  { char: '🕐', words: 'horloge heure durée' },
  { char: '📍', words: 'épingle lieu position adresse' },
  { char: '📌', words: 'punaise acté épinglé' },
  { char: '🧮', words: 'boulier calcul total chiffre' },
  { char: '💶', words: 'euro argent prix budget' },
  { char: '💰', words: 'argent budget sac coût' },
  { char: '💳', words: 'carte bancaire paiement banque' },
  { char: '🧾', words: 'reçu facture note addition' },
  { char: '🏦', words: 'banque argent établissement' },
  { char: '📈', words: 'courbe hausse graphique stats' },
  { char: '📉', words: 'courbe baisse graphique stats' },
  { char: '📊', words: 'graphique barres stats tableau' },

  { char: '✈️', words: 'avion vol transport aéroport' },
  { char: '🛫', words: 'décollage départ avion vol' },
  { char: '🛬', words: 'atterrissage arrivée avion vol' },
  { char: '🚆', words: 'train transport gare rail' },
  { char: '🚄', words: 'tgv train grande vitesse rail' },
  { char: '🚌', words: 'bus car transport' },
  { char: '🚐', words: 'van minibus navette' },
  { char: '🚗', words: 'voiture auto location transport' },
  { char: '🚕', words: 'taxi voiture transport' },
  { char: '🛵', words: 'scooter deux roues vespa' },
  { char: '🏍️', words: 'moto deux roues' },
  { char: '🚲', words: 'vélo bicyclette cyclisme' },
  { char: '⛴️', words: 'ferry bateau traversée mer' },
  { char: '🛳️', words: 'bateau croisière paquebot' },
  { char: '⛵', words: 'voilier bateau mer voile' },
  { char: '🚠', words: 'téléphérique montagne cabine' },
  { char: '🛣️', words: 'route autoroute trajet' },
  { char: '⛽', words: 'essence carburant station plein' },
  { char: '🅿️', words: 'parking stationnement place' },
  { char: '🚦', words: 'feu circulation route' },

  { char: '🏠', words: 'maison hébergement logement domicile' },
  { char: '🏡', words: 'maison jardin logement villa' },
  { char: '🏘️', words: 'quartier maisons village logements' },
  { char: '🏚️', words: 'maison abandonnée ruine vieux' },
  { char: '🏨', words: 'hôtel hébergement chambre nuit' },
  { char: '🛏️', words: 'lit chambre couchage nuit' },
  { char: '🛋️', words: 'canapé salon séjour' },
  { char: '🚪', words: 'porte entrée accès clé' },
  { char: '🔑', words: 'clé accès arrivée remise' },
  { char: '🗝️', words: 'clé ancienne accès secret' },
  { char: '🏕️', words: 'camping tente nature bivouac' },
  { char: '⛺', words: 'tente camping bivouac' },
  { char: '🏰', words: 'château fort monument visite' },
  { char: '🏛️', words: 'monument musée antique colonnes' },
  { char: '⛪', words: 'église chapelle visite religieux' },
  { char: '🕌', words: 'mosquée religieux monument' },
  { char: '🗼', words: 'tour monument visite' },
  { char: '🏟️', words: 'stade arène amphithéâtre' },
  { char: '🏙️', words: 'ville urbain skyline cité' },
  { char: '🌆', words: 'ville soir coucher urbain' },
  { char: '🌃', words: 'ville nuit urbain' },
  { char: '🏞️', words: 'parc nature paysage campagne' },
  { char: '🏖️', words: 'plage mer sable vacances' },
  { char: '🏝️', words: 'île plage tropical mer' },
  { char: '⛰️', words: 'montagne sommet randonnée' },
  { char: '🌋', words: 'volcan montagne éruption' },
  { char: '🏔️', words: 'montagne neige sommet alpes' },

  { char: '🍽️', words: 'restaurant repas manger couverts' },
  { char: '🍴', words: 'couverts repas manger restaurant' },
  { char: '🍕', words: 'pizza italie repas' },
  { char: '🍝', words: 'pâtes italie repas spaghetti' },
  { char: '🥐', words: 'croissant petit déjeuner boulangerie' },
  { char: '🥖', words: 'pain baguette boulangerie' },
  { char: '🧀', words: 'fromage apéro produit' },
  { char: '🍷', words: 'vin verre dégustation cave' },
  { char: '🍺', words: 'bière verre bar' },
  { char: '🍹', words: 'cocktail apéro bar vacances' },
  { char: '☕', words: 'café boisson pause matin' },
  { char: '🍦', words: 'glace gelato dessert' },
  { char: '🍰', words: 'gâteau dessert pâtisserie' },
  { char: '🍋', words: 'citron agrume fruit' },
  { char: '🍇', words: 'raisin vigne fruit vin' },
  { char: '🫒', words: 'olive huile apéro' },
  { char: '🥗', words: 'salade repas léger' },
  { char: '🛒', words: 'courses panier supermarché achat' },
  { char: '🏪', words: 'magasin commerce épicerie' },

  { char: '🌞', words: 'soleil beau temps météo chaud' },
  { char: '☀️', words: 'soleil météo beau chaud' },
  { char: '🌤️', words: 'soleil nuage météo' },
  { char: '☁️', words: 'nuage météo couvert cloud serveur distant' },
  { char: '🌧️', words: 'pluie météo averse' },
  { char: '⛈️', words: 'orage pluie météo' },
  { char: '❄️', words: 'neige froid hiver météo' },
  { char: '🌡️', words: 'température thermomètre chaleur météo' },
  { char: '🌊', words: 'vague mer océan baignade' },
  { char: '🌅', words: 'lever soleil aube matin' },
  { char: '🌇', words: 'coucher soleil soir' },
  { char: '🌙', words: 'lune nuit plus tard soir' },
  { char: '⭐', words: 'étoile favori note qualité' },
  { char: '🌟', words: 'étoile brillante favori coup de cœur' },
  { char: '🔥', words: 'feu urgent chaud tendance' },
  { char: '🌱', words: 'pousse début nouveau nature' },
  { char: '🌳', words: 'arbre nature parc forêt' },
  { char: '🌲', words: 'sapin forêt nature montagne' },
  { char: '🌻', words: 'tournesol fleur toscane été' },
  { char: '🌺', words: 'fleur nature jardin' },
  { char: '🍂', words: 'automne feuilles saison' },
  { char: '🐕', words: 'chien animal compagnon' },
  { char: '🐈', words: 'chat animal compagnon' },
  { char: '🐬', words: 'dauphin mer animal' },
  { char: '🦋', words: 'papillon nature léger' },

  { char: '🎡', words: 'attraction grande roue fête parc' },
  { char: '🎢', words: 'attraction montagnes russes parc' },
  { char: '🎠', words: 'manège carrousel attraction enfants' },
  { char: '🎭', words: 'théâtre spectacle culture masque' },
  { char: '🎨', words: 'art peinture musée culture' },
  { char: '🖼️', words: 'tableau cadre écran musée' },
  { char: '🎪', words: 'cirque chapiteau spectacle' },
  { char: '🎬', words: 'cinéma film clap tournage' },
  { char: '🎵', words: 'musique note concert' },
  { char: '🎤', words: 'micro concert chant' },
  { char: '📷', words: 'photo appareil souvenir' },
  { char: '🎥', words: 'caméra vidéo film' },
  { char: '🥾', words: 'randonnée chaussure marche trek' },
  { char: '🚶', words: 'marche piéton balade à pied' },
  { char: '🧗', words: 'escalade grimpe sport montagne' },
  { char: '🏊', words: 'nage piscine baignade sport' },
  { char: '🛁', words: 'bain thermes spa détente' },
  { char: '♨️', words: 'thermes source chaude spa vapeur' },
  { char: '⚽', words: 'football sport ballon' },
  { char: '🎿', words: 'ski neige sport hiver' },

  { char: '💡', words: 'idée ampoule lumière suggestion' },
  { char: '🤔', words: 'réflexion à trancher question doute' },
  { char: '❓', words: 'question interrogation inconnu' },
  { char: '❗', words: 'important attention exclamation' },
  { char: '⚠️', words: 'attention avertissement danger' },
  { char: '🚧', words: 'chantier en cours travaux' },
  { char: '✅', words: 'fait validé coche terminé' },
  { char: '☑️', words: 'coché case validé' },
  { char: '❌', words: 'non erreur croix refusé' },
  { char: '🚫', words: 'interdit abandonné refusé' },
  { char: '⏸️', words: 'pause attente suspendu' },
  { char: '▶️', words: 'lancer démarrer lecture' },
  { char: '🔁', words: 'répéter boucle récurrent' },
  { char: '🔄', words: 'synchro rafraîchir actualiser cycle' },
  { char: '↕️', words: 'ordre haut bas déplacer' },
  { char: '🔀', words: 'mélanger aléatoire ordre' },
  { char: '🔝', words: 'haut priorité top premier' },
  { char: '🆕', words: 'nouveau neuf récent' },
  { char: '🔢', words: 'chiffres nombre numéro' },
  { char: '🔤', words: 'lettres texte alphabet' },

  { char: '🔎', words: 'recherche loupe explorer browse' },
  { char: '🔍', words: 'loupe recherche zoom détail' },
  { char: '🗂️', words: 'classeur dossiers rangement onglets' },
  { char: '📁', words: 'dossier fichier rangement' },
  { char: '📄', words: 'document page doc fichier' },
  { char: '📝', words: 'note écrire saisie rédiger' },
  { char: '✏️', words: 'crayon modifier éditer écrire' },
  { char: '🖊️', words: 'stylo écrire signer' },
  { char: '📋', words: 'presse-papier liste checklist' },
  { char: '📎', words: 'trombone pièce jointe lien' },
  { char: '🔗', words: 'lien url chaîne relier' },
  { char: '📚', words: 'livres doc référence lecture' },
  { char: '📖', words: 'livre ouvert lecture guide' },
  { char: '🗒️', words: 'bloc-notes notes mémo' },
  { char: '🗃️', words: 'fichier boîte modèle données' },
  { char: '🗄️', words: 'classeur archives stockage' },
  { char: '📦', words: 'boîte colis archivé paquet' },
  { char: '🏷️', words: 'étiquette tag libellé' },
  { char: '🔖', words: 'marque-page signet favori' },
  { char: '📬', words: 'boîte aux lettres courrier message' },
  { char: '✉️', words: 'email courrier message' },
  { char: '📞', words: 'téléphone appel contact' },
  { char: '💬', words: 'bulle message discussion session' },
  { char: '🔔', words: 'cloche notification alerte rappel' },

  { char: '🧩', words: 'pièce puzzle ui composant brique' },
  { char: '🖥️', words: 'écran ordinateur bureau' },
  { char: '💻', words: 'ordinateur portable code dev' },
  { char: '📱', words: 'téléphone mobile écran app' },
  { char: '⌨️', words: 'clavier saisie raccourci' },
  { char: '🖱️', words: 'souris clic pointeur' },
  { char: '🐛', words: 'bug insecte erreur fix' },
  { char: '🔌', words: 'prise intégration branchement api' },
  { char: '⚙️', words: 'réglage paramètre engrenage config' },
  { char: '🛠️', words: 'outils réparer bricoler chantier' },
  { char: '🔧', words: 'clé outil réparer réglage' },
  { char: '🧹', words: 'balai nettoyage refacto ménage' },
  { char: '🧪', words: 'test éprouvette expérience essai' },
  { char: '🚀', words: 'fusée lancement rapide déploiement' },
  { char: '🧠', words: 'cerveau réflexion idée mémoire' },
  { char: '🔐', words: 'cadenas sécurité clé accès' },
  { char: '💾', words: 'sauvegarde disquette enregistrer' },
  { char: '🗑️', words: 'poubelle supprimer jeter' },

  { char: '👤', words: 'personne profil utilisateur voyageur' },
  { char: '👥', words: 'personnes groupe voyageurs équipe' },
  { char: '👨‍👩‍👧', words: 'famille groupe voyageurs enfants' },
  { char: '🧑‍🤝‍🧑', words: 'amis groupe deux personnes' },
  { char: '👋', words: 'salut bonjour accueil' },
  { char: '👍', words: 'pouce ok validé bien' },
  { char: '👎', words: 'pouce bas non refusé' },
  { char: '🙏', words: 'merci prière s’il te plaît' },
  { char: '❤️', words: 'cœur favori aimé coup de cœur' },
  { char: '💛', words: 'cœur jaune favori' },
  { char: '🎉', words: 'fête bravo célébration' },
  { char: '🎁', words: 'cadeau surprise offrir' },
  { char: '🇮🇹', words: 'italie drapeau italien toscane' },
  { char: '🇫🇷', words: 'france drapeau français' },
  { char: '🍀', words: 'trèfle chance porte-bonheur' },
];

// A needle matches the start of any keyword: « pla » finds « plage » and « plan », not « emplacement ».
function searchEmojis(needle) {
  const trimmed = needle.trim().toLowerCase();
  if (!trimmed) return EMOJIS;
  return EMOJIS.filter((entry) => entry.words.split(' ').some((word) => word.startsWith(trimmed)));
}
